name: A simple Docker action
on:
  issues:
    types: [opened, edited, labeled]
jobs:
  user-and-time:
    runs-on: ubuntu
    name: Running a simple BASH script
    steps:
    - name: A simple BASH script
      id: BASH
      uses: bisseta/cicd_git_actions@main
